### ISSUE TITLE
qemu boot is sometimes hanging

### ISSUE THREAD

**Issue by samoht** [linuxkit/linuxkit#1403]
On my new NUC, booting moby with `scripts/qemu.sh` sometimes hangs when using KVM. The boot sequence seems stuck for something like a few seconds to a few minutes between this 2 lines:

```
clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x19f216c168a, max_idle_ns: 440795268188 ns
[ .... hanging here .... ]
Hangcheck: starting hangcheck timer 0.9.1 (tick is 180 seconds, margin is 60 seconds).
```

Some info about my box:
```
$ uname -a
Linux porto 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Also, it seems that the issue completely disappear when I reboot, and seems to come back the next day (I've done that only once, so it's maybe a bit early to generalise...). I have also tried to disable kvm by commenting out the `DEVKVM` bits, and the VM was booting fast. 

I am not sure how to debug that issue, so please let me know if you need more data.

**Comment by SvenDowideit** [comment]
I was getting a situation where qemu was hanging (with 100% cpu use) at 

```
Freeing SMP alternatives memory: 24K (ffffffff8c0c0000 - ffffffff8c0c6000)
```
it stopped happening when I added myself to the kvm group (yup, new system), or if i removed `-device virtio-rng-pci`

in my jetlagged state, I spent way too much time trying to work out what i broke.

**Comment by justincormack** [comment]
@SvenDowideit thats very odd. cc @ijc25

**Comment by ijc25** [comment]
No idea, but removing `-device virtio-rng-pci` seems interesting. Perhaps it is awaiting some entropy from the host which will never arrive due to some quirk of running in TCG mode or something?

**Comment by ijc25** [comment]
Is `virtio-rng-pci` the only virtio device? I bit of googling seems to be suggesting that there are (or have been) some virtio related hangs in the past, so it might just be generic virtio and not specific to `virtio-rng-pci`.

**Comment by rn** [comment]
Is this still an issue, can it be closed?

**Comment by rkgade** [comment]
I am facing the same issue.

 :>$ uname -a
Linux hydrogen 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux


 :>$ linuxkit run -networking  bridge,docker0 redis-os
[    0.000000] Linux version 4.9.47-linuxkit (root@e1ede117fb1e) (gcc version 6.3.0 (Alpine 6.3.0) ) #1 SMP Mon Sep 4 16:11:11 UTC 2017
[    0.000000] Command line: console=tty0 console=ttyS0 console=ttyAMA0
[    0.000000] x86/fpu: Legacy x87 FPU detected.
[    0.000000] x86/fpu: Using 'eager' FPU context switches.
[    0.000000] e820: BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000003ffdefff] usable
[    0.000000] BIOS-e820: [mem 0x000000003ffdf000-0x000000003fffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000b0000000-0x00000000bfffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fed1c000-0x00000000fed1ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000feffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.8 present.
[    0.000000] Hypervisor detected: KVM
[    0.000000] e820: last_pfn = 0x3ffdf max_arch_pfn = 0x400000000
[    0.000000] x86/PAT: PAT not supported by CPU.
[    0.000000] x86/PAT: Configuration [0-7]: WB  WT  UC- UC  WB  WT  UC- UC  
[    0.000000] found SMP MP-table at [mem 0x000f6a90-0x000f6a9f] mapped at [ffff92f3400f6a90]
[    0.000000] RAMDISK: [mem 0x3cdf8000-0x3ffcffff]
[    0.000000] ACPI: Early table checksum verification disabled
[    0.000000] ACPI: RSDP 0x00000000000F68C0 000014 (v00 BOCHS )
[    0.000000] ACPI: RSDT 0x000000003FFE2052 000034 (v01 BOCHS  BXPCRSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACP 0x000000003FFE1EF2 000074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[    0.000000] ACPI: DSDT 0x000000003FFE0040 001EB2 (v01 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACS 0x000000003FFE0000 000040
[    0.000000] ACPI: APIC 0x000000003FFE1F66 000078 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
[    0.000000] ACPI: HPET 0x000000003FFE1FDE 000038 (v01 BOCHS  BXPCHPET 00000001 BXPC 00000001)
[    0.000000] ACPI: MCFG 0x000000003FFE2016 00003C (v01 BOCHS  BXPCMCFG 00000001 BXPC 00000001)
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: cpu 0, msr 0:3ffdd001, primary cpu clock
[    0.000000] kvm-clock: using sched offset of 199468003 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[    0.000000]   DMA32    [mem 0x0000000001000000-0x000000003ffdefff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
[    0.000000]   node   0: [mem 0x0000000000100000-0x000000003ffdefff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x000000003ffdefff]
[    0.000000] ACPI: PM-Timer IO Port: 0x608
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
[    0.000000] IOAPIC[0]: apic_id 0, version 17, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] ACPI: HPET id: 0x8086a201 base: 0xfed00000
[    0.000000] smpboot: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] e820: [mem 0x40000000-0xafffffff] available for PCI devices
[    0.000000] Booting paravirtualized kernel on KVM
[    0.000000] clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.000000] setup_percpu: NR_CPUS:128 nr_cpumask_bits:128 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] percpu: Embedded 35 pages/cpu @ffff92f37ca00000 s105240 r8192 d29928 u2097152
[    0.000000] KVM setup async PF for cpu 0
[    0.000000] kvm-stealtime: cpu 0, msr 3ca0d580
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 257896
[    0.000000] Kernel command line: console=tty0 console=ttyS0 console=ttyAMA0
[    0.000000] PID hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes)
[    0.000000] Memory: 963124K/1048052K available (8032K kernel code, 1366K rwdata, 2696K rodata, 1380K init, 568K bss, 84928K reserved, 0K cma-reserved)
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  Build-time adjustment of leaf fanout to 64.
[    0.000000]  RCU restricting CPUs from NR_CPUS=128 to nr_cpu_ids=1.
[    0.000000] RCU: Adjusting geometry for rcu_fanout_leaf=64, nr_cpu_ids=1
[    0.000000] NR_IRQS:8448 nr_irqs:256 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty0] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] clocksource: hpet: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604467 ns
[    0.000000] tsc: Detected 2594.106 MHz processor
[    0.128881] Calibrating delay loop (skipped) preset value.. 5188.21 BogoMIPS (lpj=25941060)
[    0.131018] pid_max: default: 32768 minimum: 301
[    0.132184] ACPI: Core revision 20160831
[    0.133826] ACPI: 1 ACPI AML tables successfully acquired and loaded
[    0.135461] Security Framework initialized
[    0.136493] Yama: becoming mindful.
[    0.137418] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.138840] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes)
[    0.140905] CPU: Physical Processor ID: 0
[    0.142039] Last level iTLB entries: 4KB 0, 2MB 0, 4MB 0
[    0.143406] Last level dTLB entries: 4KB 0, 2MB 0, 4MB 0, 1GB 0
[    0.154648] Freeing SMP alternatives memory: 20K
[    0.156992] ftrace: allocating 35509 entries in 139 pages
[    0.191507] smpboot: Max logical packages: 1
[    0.192670] x2apic enabled
[    0.193561] Switched APIC routing to physical x2apic.
[    0.195484] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.307773] smpboot: CPU0: Intel QEMU Virtual CPU version 2.5+ (family: 0x6, model: 0x6, stepping: 0x3)
[    0.309661] Performance Events: PMU not available due to virtualization, using software events only.
[    0.311573] x86: Booted up 1 node, 1 CPUs
[    0.312259] smpboot: Total of 1 processors activated (5188.21 BogoMIPS)
[    0.313437] devtmpfs: initialized
[    0.314049] x86/mm: Memory block size: 128MB
[    0.318519] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.320369] futex hash table entries: 256 (order: 2, 16384 bytes)
[    0.321355] NET: Registered protocol family 16
[    0.322206] cpuidle: using governor ladder
[    0.323166] cpuidle: using governor menu
[    0.324289] ACPI: bus type PCI registered
[    0.325467] PCI: MMCONFIG for domain 0000 [bus 00-ff] at [mem 0xb0000000-0xbfffffff] (base 0xb0000000)
[    0.327613] PCI: MMCONFIG at [mem 0xb0000000-0xbfffffff] reserved in E820
[    0.329235] PCI: Using configuration type 1 for base access
[    0.331904] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    0.332977] ACPI: Added _OSI(Module Device)
[    0.333621] ACPI: Added _OSI(Processor Device)
[    0.334516] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.335496] ACPI: Added _OSI(Processor Aggregator Device)
[    0.338778] ACPI: Interpreter enabled
[    0.339709] ACPI: (supports S0 S5)
[    0.340575] ACPI: Using IOAPIC for interrupt routing
[    0.341793] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.345533] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.346859] acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments MSI]
[    0.349227] acpi PNP0A08:00: _OSC: OS now controls [PCIeHotplug PME PCIeCapability]
[    0.351324] PCI host bridge to bus 0000:00
[    0.352435] pci_bus 0000:00: root bus resource [io  0x0000-0x0cf7 window]
[    0.354086] pci_bus 0000:00: root bus resource [io  0x0d00-0xffff window]
[    0.355838] pci_bus 0000:00: root bus resource [mem 0x000a0000-0x000bffff window]
[    0.357642] pci_bus 0000:00: root bus resource [mem 0xc0000000-0xfebfffff window]
[    0.359456] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.397451] pci 0000:00:1f.0: quirk: [io  0x0600-0x067f] claimed by ICH6 ACPI/GPIO/TCO
[    0.412191] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 *10 11)
[    0.414032] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 *10 11)
[    0.415762] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 10 *11)
[    0.418205] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 10 *11)
[    0.419938] ACPI: PCI Interrupt Link [LNKE] (IRQs 5 *10 11)
[    0.421677] ACPI: PCI Interrupt Link [LNKF] (IRQs 5 *10 11)
[    0.423405] ACPI: PCI Interrupt Link [LNKG] (IRQs 5 10 *11)
[    0.425137] ACPI: PCI Interrupt Link [LNKH] (IRQs 5 10 *11)
[    0.426823] ACPI: PCI Interrupt Link [GSIA] (IRQs *16)
[    0.428172] ACPI: PCI Interrupt Link [GSIB] (IRQs *17)
[    0.429714] ACPI: PCI Interrupt Link [GSIC] (IRQs *18)
[    0.431327] ACPI: PCI Interrupt Link [GSID] (IRQs *19)
[    0.432571] ACPI: PCI Interrupt Link [GSIE] (IRQs *20)
[    0.433751] ACPI: PCI Interrupt Link [GSIF] (IRQs *21)
[    0.434972] ACPI: PCI Interrupt Link [GSIG] (IRQs *22)
[    0.436186] ACPI: PCI Interrupt Link [GSIH] (IRQs *23)
[    0.437487] ACPI: Enabled 1 GPEs in block 00 to 3F
[    0.438736] SCSI subsystem initialized
[    0.439556] ACPI: bus type USB registered
[    0.440427] usbcore: registered new interface driver usbfs
[    0.441518] usbcore: registered new interface driver hub
[    0.442559] usbcore: registered new device driver usb
[    0.443584] pps_core: LinuxPPS API ver. 1 registered
[    0.444606] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.446330] PTP clock support registered
[    0.447183] wmi: Mapper loaded
[    0.448220] PCI: Using ACPI for IRQ routing
[    0.505831] NetLabel: Initializing
[    0.506470] NetLabel:  domain hash size = 128
[    0.507157] NetLabel:  protocols = UNLABELED CIPSOv4
[    0.508051] NetLabel:  unlabeled traffic allowed by default
[    0.509199] HPET: 3 timers in total, 0 timers will be used for per-cpu timer
[    0.510502] hpet0: at MMIO 0xfed00000, IRQs 2, 8, 0
[    0.511717] hpet0: 3 comparators, 64-bit 100.000000 MHz counter
[    0.518029] clocksource: Switched to clocksource kvm-clock
[    0.529217] VFS: Disk quotas dquot_6.6.0
[    0.530009] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.530998] FS-Cache: Loaded
[    0.531583] CacheFiles: Loaded
[    0.532117] pnp: PnP ACPI init
[    0.533175] pnp: PnP ACPI: found 5 devices
[    0.540013] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    0.541459] NET: Registered protocol family 2
[    0.542362] TCP established hash table entries: 8192 (order: 4, 65536 bytes)
[    0.543711] TCP bind hash table entries: 8192 (order: 5, 131072 bytes)
[    0.544955] TCP: Hash tables configured (established 8192 bind 8192)
[    0.546123] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.547033] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.547976] NET: Registered protocol family 1
[    0.548721] pci 0000:00:01.0: Video device with shadowed ROM at [mem 0x000c0000-0x000dffff]
[    0.550386] Unpacking initramfs...
[    1.293306] Freeing initrd memory: 51040K
[    1.294812] PCLMULQDQ-NI instructions are not detected.
[    1.295597] AVX or AES-NI instructions are not detected.
[    1.296636] CPU feature 'AVX registers' is not supported.
[    1.297692] CPU feature 'AVX registers' is not supported.
[    1.298815] CPU feature 'AVX registers' is not supported.
[    1.299666] CPU feature 'AVX registers' is not supported.
[    1.300891] AVX2 or AES-NI instructions are not detected.
[    1.301921] AVX2 instructions are not detected.
[    1.302972] audit: initializing netlink subsys (disabled)
[    1.304058] audit: type=2000 audit(1504783229.590:1): initialized
[    1.305478] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    1.306883] FS-Cache: Netfs 'cifs' registered for caching
[    1.307971] fuse init (API version 7.26)
[    1.308880] SGI XFS with ACLs, security attributes, no debug enabled
[    1.310184] 9p: Installing v9fs 9p2000 file system support
[    1.311317] FS-Cache: Netfs '9p' registered for caching
[    1.313237] NET: Registered protocol family 38
[    1.314170] Key type asymmetric registered
[    1.314988] Asymmetric key parser 'x509' registered
[    1.315975] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    1.317575] io scheduler noop registered
[    1.318290] io scheduler deadline registered (default)
[    1.319113] io scheduler cfq registered
[    1.320013] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    1.321089] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    1.322354] shpchp: Standard Hot Plug PCI Controller Driver version: 0.4
[    1.323624] hv_vmbus: registering driver hyperv_fb
[    1.324621] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    1.326134] ACPI: Power Button [PWRF]
[    1.327007] GHES: HEST is not enabled!
[    1.328137] ACPI: PCI Interrupt Link [GSIG] enabled at IRQ 22
[    1.330541] ACPI: PCI Interrupt Link [GSIH] enabled at IRQ 23
[    1.332587] xenfs: not registering filesystem on non-xen platform
[    1.333899] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    1.357825] 00:04: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    1.360216] Non-volatile memory driver v1.3
[    1.361422] Hangcheck: starting hangcheck timer 0.9.1 (tick is 180 seconds, margin is 60 seconds).
[    1.363549] random: fast init done
[    1.364554] random: crng init done
[    1.366190] loop: module loaded
[    1.367168] nbd: registered device at major 43
[    1.369234] lpc_ich 0000:00:1f.0: I/O space for GPIO uninitialized
[    1.370455] VMware PVSCSI driver - version 1.0.7.0-k
[    1.371432] hv_vmbus: registering driver hv_storvsc
[    1.372738] ACPI: PCI Interrupt Link [GSIA] enabled at IRQ 16
[    1.374271] ahci 0000:00:1f.2: AHCI 0001.0000 32 slots 6 ports 1.5 Gbps 0x3f impl SATA mode
[    1.375906] ahci 0000:00:1f.2: flags: 64bit ncq only 
[    1.377655] scsi host0: ahci
[    1.378354] scsi host1: ahci
[    1.378988] scsi host2: ahci
[    1.379710] scsi host3: ahci
[    1.380393] scsi host4: ahci
[    1.380952] scsi host5: ahci
[    1.381533] ata1: SATA max UDMA/133 abar m4096@0xfebd2000 port 0xfebd2100 irq 24
[    1.382639] ata2: SATA max UDMA/133 abar m4096@0xfebd2000 port 0xfebd2180 irq 24
[    1.384327] ata3: SATA max UDMA/133 abar m4096@0xfebd2000 port 0xfebd2200 irq 24
[    1.386671] ata4: SATA max UDMA/133 abar m4096@0xfebd2000 port 0xfebd2280 irq 24
[    1.388777] ata5: SATA max UDMA/133 abar m4096@0xfebd2000 port 0xfebd2300 irq 24
[    1.390899] ata6: SATA max UDMA/133 abar m4096@0xfebd2000 port 0xfebd2380 irq 24
[    1.393657] tun: Universal TUN/TAP device driver, 1.6
[    1.395154] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.397707] VMware vmxnet3 virtual NIC driver - version 1.4.a.0-k-NAPI
[    1.399054] hv_vmbus: registering driver hv_netvsc
[    1.400290] Fusion MPT base driver 3.04.20
[    1.401415] Copyright (c) 1999-2008 LSI Corporation
[    1.402682] Fusion MPT SPI Host driver 3.04.20
[    1.403936] i8042: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
[    1.406815] serio: i8042 KBD port at 0x60,0x64 irq 1
[    1.408053] serio: i8042 AUX port at 0x60,0x64 irq 12
[    1.409371] hv_vmbus: registering driver hyperv_keyboard
[    1.410713] mousedev: PS/2 mouse device common for all mice
[    1.412280] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input1
[    1.414474] input: PC Speaker as /devices/platform/pcspkr/input/input3
[    1.415585] rtc_cmos 00:00: RTC can wake from S4
[    1.416470] rtc_cmos 00:00: rtc core: registered rtc_cmos as rtc0
[    1.417483] rtc_cmos 00:00: alarms up to one day, y3k, 114 bytes nvram, hpet irqs
[    1.418625] i2c /dev entries driver
[    1.419265] device-mapper: ioctl: 4.35.0-ioctl (2016-06-23) initialised: dm-devel@redhat.com
[    1.421399] usbcore: registered new interface driver usbhid
[    1.422267] usbhid: USB HID core driver
[    1.422922] hv_utils: Registering HyperV Utility Driver
[    1.423679] hv_vmbus: registering driver hv_util
[    1.424373] hv_vmbus: registering driver hv_balloon
[    1.425109] oprofile: using NMI interrupt.
[    1.425870] GACT probability on
[    1.426560] Mirror/redirect action on
[    1.427313] Simple TC action Loaded
[    1.428229] u32 classifier
[    1.428976]     Performance counters on
[    1.429929]     input device check on
[    1.430862]     Actions configured
[    1.431514] Netfilter messages via NETLINK v0.30.
[    1.432441] nfnl_acct: registering with nfnetlink.
[    1.433490] nf_conntrack version 0.5.0 (8192 buckets, 32768 max)
[    1.434952] ctnetlink v0.93: registering with nfnetlink.
[    1.436223] nf_tables: (c) 2007-2009 Patrick McHardy <kaber@trash.net>
[    1.437733] nf_tables_compat: (c) 2012 Pablo Neira Ayuso <pablo@netfilter.org>
[    1.439540] xt_time: kernel timezone is -0000
[    1.440606] ip_set: protocol 6
[    1.441400] IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)
[    1.442808] IPVS: Connection hash table configured (size=4096, memory=64Kbytes)
[    1.444622] IPVS: Creating netns size=2104 id=0
[    1.445397] IPVS: ipvs loaded.
[    1.445906] IPVS: [rr] scheduler registered.
[    1.446682] IPVS: [wrr] scheduler registered.
[    1.447462] IPVS: [lc] scheduler registered.
[    1.448123] IPVS: [wlc] scheduler registered.
[    1.448831] IPVS: [fo] scheduler registered.
[    1.449475] IPVS: [ovf] scheduler registered.
[    1.450255] IPVS: [lblc] scheduler registered.
[    1.451115] IPVS: [lblcr] scheduler registered.
[    1.452101] IPVS: [dh] scheduler registered.
[    1.452949] IPVS: [sh] scheduler registered.
[    1.453789] IPVS: [sed] scheduler registered.
[    1.454651] IPVS: [nq] scheduler registered.
[    1.455483] IPVS: ftp: loaded support on port[0] = 21
[    1.456491] ipip: IPv4 and MPLS over IPv4 tunneling driver
[    1.457658] gre: GRE over IPv4 demultiplexor driver
[    1.458759] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.459768] ipt_CLUSTERIP: ClusterIP Version 0.8 loaded successfully
[    1.460706] arp_tables: arp_tables: (C) 2002 David S. Miller
[    1.462066] NET: Registered protocol family 10
[    1.463409] ip6_tables: (C) 2000-2006 Netfilter Core Team
[    1.465149] NET: Registered protocol family 17
[    1.466095] Bridge firewalling registered
[    1.466756] Ebtables v2.0 registered
[    1.467377] 8021q: 802.1Q VLAN Support v1.8
[    1.468208] 9pnet: Installing 9P2000 support
[    1.469054] Key type dns_resolver registered
[    1.469945] microcode: sig=0x663, pf=0x1, revision=0x1
[    1.470794] microcode: Microcode Update Driver: v2.01 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
[    1.472160] registered taskstats version 1
[    1.475755] Key type big_key registered
[    1.477864] Key type encrypted registered
[    1.479004] rtc_cmos 00:00: setting system clock to 2017-09-07 11:20:29 UTC (1504783229)
[    1.722277] ata6: SATA link down (SStatus 0 SControl 300)
[    1.725852] ata3: SATA link up 1.5 Gbps (SStatus 113 SControl 300)
[    1.728749] ata2: SATA link down (SStatus 0 SControl 300)
[    1.730663] ata4: SATA link down (SStatus 0 SControl 300)
[    1.732589] ata1: SATA link down (SStatus 0 SControl 300)
[    1.734525] ata5: SATA link down (SStatus 0 SControl 300)
[    1.736196] ata3.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    1.737276] ata3.00: applying bridge limits
[    1.738264] ata3.00: configured for UDMA/100
[    1.739355] scsi 2:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    1.758419] sr 2:0:0:0: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[    1.761282] cdrom: Uniform CD-ROM driver Revision: 3.20
[    1.764085] sr 2:0:0:0: Attached scsi generic sg0 type 5
[    1.768780] Freeing unused kernel memory: 1380K
[    1.770243] Write protecting the kernel read-only data: 12288k
[    1.771816] Freeing unused kernel memory: 144K
[    1.776831] Freeing unused kernel memory: 1400K

Welcome to LinuxKit

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
          {                       /  ===-
           \______ O           __/
             \    \         __/
              \____\_______/

[    2.115517] 8021q: adding VLAN 0 to HW filter on device eth0
[    2.338218] tsc: Refined TSC clocksource calibration: 2594.109 MHz
[    2.341344] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x25647f0d2d3, max_idle_ns: 440795228342 ns

<HANGS HERE>

**Comment by rn** [comment]
Closing as this issue seems ancient and hasn't received updates nor have we had other folks reporting the issue.
