### ISSUE TITLE
kernel: Should we allow patches that are not destined for upstream?

### ISSUE THREAD

**Issue by tych0** [linuxkit/linuxkit#1628]
Here's an issue to discuss whether we allow patches that are not destined for upstream (or destination unknown, e.g. in development but no maintainer has definitely said they want the feature, e.g. shiftfs).

**Comment by avsm** [comment]
It would be good not to have these in the mainline kernels we ship, since chances of them applying to all the vanilla kernel variants is low.  Can we keep them constrained to a particular feature (e.g. landlock) so that only users of that feature in the yaml file will have restrictions on the kernel version they choose?

The sorts of kernel patches we might want are:
- drivers that are out-of-tree - fairly easy to activate as a patch, but would also often come with associated userspace tools and so we might want to build as a module+container for userspace tools.
- feature specific so constrained to a single directory/project (like #1623)
- broader patches like okernel which touch subsystems like virtual memory that are clearly not for general consumption

**Comment by justincormack** [comment]
We dont apply our patches to the vanilla kernels for testing or to projects, this is just about whether we should apply them in the kernel we ship that we eg use for Editions.

**Comment by riyazdf** [comment]
I think it's a good idea to include patches that we agree on in the Editions kernels, especially on `edge` / `beta` channels.  We'd like a way to push the status quo of upstream kernel features (especially security improvements), and importantly need a way to provide them to users and prove to maintainers that the patch is upstreamable and provides value.

We also discussed at the summit to aggregate security features into a `security-edge` channel kernel so that we could run a linuxkit kernel with landlock + ebpf hardening (@tych0's patch) + wireguard.

**Comment by justincormack** [comment]
A `security-edge` channel is very different. We can do anything there; its basically an aggregation of projects. We could also have a hardened mainstream channel I guess (eg I would like to have things like 32 bit emulation removed; there are things that some customers want but many do not). But if things are rejected by upstream (apparently in any form) its more problematic - there is no point ending up as grsecurity mark 2, with a subset of their patches that are still not going upstream.

**Comment by riyazdf** [comment]
Agree - what if we had a flow like the following?

- `security-edge` channel for a combination of bleeding edge, ex: landlock + ebpf hardening + wireguard - we have to make this easily consumable, whether it's in a project or some other way

- `hardened` channel as @justincormack mentions that at first only tweaks already upstreamed features and configurations, but also can pick up features from `security-edge` once we deem they are ready.  Again, has to be easy for the community to consume, I'm thinking it should live in the `kernel` subdir.

- features from `hardened` can then be promoted to editions once we deem they are ready and have interest from upstream maintainers, with the goal of upstreaming the features.

Admittedly there are some details to work out with the promotion process between stages - but for now I can start the `security-edge` project and also the `hardened` kernel if we think this makes sense?

**Comment by tych0** [comment]
I guess the question is really: what do we want to do about maintainers who consider this stuff to be paranoia? One path is to try to use linuxkit to leverage support for these kinds of issues, and another is to simply follow upstream's recommendations.

In the case of ebpf we could drop the patch and accept the maintainer's recommendation to just disable the JIT, but that will make our landlock/seccomp policies (which run on every syscall) slower. If we're security focused and don't want to carry patches that have been rejected by upstream, it seems like we need to disable the JIT.

**Comment by justincormack** [comment]
Well for this specific case, it sounds like you should open an issue for that patch and explain in detail what the threat is, what the mitigation options are and the pros and cons.

**Comment by tych0** [comment]
Sounds good, I opened #1739

**Comment by rn** [comment]
closing. seems outdated
