### ISSUE TITLE
Support non bzImage kernels

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1630]
We didnt really think when designing the kernel support initially, so we hardcoded `bzImage` in various places, and this needs to be fixed for 
(a) architectures that use other formats eg aarch64 https://github.com/docker/linuxkit/pull/1620
(b) projects/boot methods that want to use another format eg Clear Containers https://github.com/docker/linuxkit/pull/1625

There are a few options - either we collect all the potential kernels that we find in the kernel image (bzImage, zImage, vmlinux etc) and then pass them all to the output methods so they can select the one we want, or we can have a selector in the kernel image stanza saying which one to use (with a per architecture default).

The second method is probably simpler to implement...

**Comment by ijc25** [comment]
Mostly the `bz` in `bzImage` and the `z` in `zImage` are internal implementation details of the bootable image, the external interface (or boot protocol) is the same across all the variants for an architecture -- so the bootloader always calls the image in the same manner irrespective (the difference is in the compression used for the "payload", but since the matching decompressor is embedded into the image nothing needs to know that).

So we can most likely get by with picking a more generic name (like `kernel`) for the filename within the kernel pkg/image and have the kernel build pick the right file to install per arch (so `bzImage` for x86, `zImage` for arm32, I've forgotten for arm64 -- might be just `Image` or it might be `Image.gz`). Consumers don't care about that and just pickup `kernel` and the platform firmware/bootloader would naturally know how to boot that platform's default kernel type.

There might be one exception which would be situations where some platform wants the raw kernel ELF rather than the bootable artefact. Not sure if we have any of those? On x86 you can actually get the ELF out of the `bzImage` so things which used to require the raw ELF (like Xen) can work with the `bzImage` now, I don't think e.g. ARM has the same property though.

Another thing a consumer might want is the full unstripped ELF for use with a debugger, but that's a bit orthogonal to this issue I think.

**Comment by justincormack** [comment]
@ijc25 Clear Containers uses the `vmlinux` directly to boot. But yes I think just having "kernel" would work fine.

**Comment by ijc25** [comment]
> Clear Containers

I knew I had an example in mind when I wrote the bulk of that comment on Wednesday (before I went on PTO) but I couldn't for the life of me remember it when I came to hit the "Comment" button today! I should have reread the original issue where you even mentioned it...
