### ISSUE TITLE
Cannot connect to GCP

### ISSUE THREAD

**Issue by zepouet** [linuxkit/linuxkit#1775]
**Description**

I am trying to connect to GCP but few documentation about it.
I used this tutorial http://collabnix.com/archives/2929 very nice but it seems error gives few help to understand the problem. 
It seems we need to use keys but no way to do it.

If you have more informations about, it is nice.
Thanks

```
 ✘ nicolas@macbook-pro-de-nicolas  ~/software/linuxkit   master ●  linuxkit push gcp
Please specify the prefix to the image to push
USAGE: linuxkit push gcp [options] [name]

'name' specifies the full path of an image file which will be uploaded
Options:

  -bucket string
    	GS Bucket to upload to. *Required*
  -family string
    	GCP Image Family. A group of images where the family name points to the most recent image. *Optional*
  -img-name string
    	Overrides the Name used to identify the file in Google Storage and Image. Defaults to [name]
  -keys string
    	Path to Service Account JSON key file
  -project string
    	GCP Project Name
  -public
    	Select if file on GS should be public. *Optional*
```

**Describe the results you received:**
Connection success

**Describe the results you expected:**
Help about error if parameter are wrong.

**Comment by ajeetraina** [comment]
Did you supply the complete command?

sudo linuxkit push gcp -project synthetic-diode-161714 -bucket mygcp
gcpwithdocker.img.tar.gz

where project name,  bucket name and image had to be supplied.


On 06-May-2017 2:02 PM, "Nicolas Muller" <notifications@github.com> wrote:

*Description*

I am trying to connect to GCP but few documentation about it.
I used this tutorial http://collabnix.com/archives/2929 very nice but it
seems error gives few help to understand the problem.
It seems we need to use keys but no way to do it.

If you have more informations about, it is nice.
Thanks

 ✘ nicolas@macbook-pro-de-nicolas  ~/software/linuxkit   master ● 
linuxkit push gcp
Please specify the prefix to the image to push
USAGE: linuxkit push gcp [options] [name]

'name' specifies the full path of an image file which will be uploaded
Options:

  -bucket string
    	GS Bucket to upload to. *Required*
  -family string
    	GCP Image Family. A group of images where the family name points
to the most recent image. *Optional*
  -img-name string
    	Overrides the Name used to identify the file in Google Storage
and Image. Defaults to [name]
  -keys string
    	Path to Service Account JSON key file
  -project string
    	GCP Project Name
  -public
    	Select if file on GS should be public. *Optional*

*Describe the results you received:*
Connection success

*Describe the results you expected:*
Help about error if parameter are wrong.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/issues/1775>, or mute the thread

**Comment by zepouet** [comment]
Hello,

Yes I previously use the gcloud command to login into.
I use `linuxkit push gcp -project mylinuxkit-166808 -bucket mygcp13000 gcpwithdocker.img.tar.gz` but always `FATA[0000] Unable to connect to GCP`

I will test with another environment. I tested it with MacOS Sierra (10.12.4) but I will do it again with a Linux. 

Thanks for your help and the article :)

**Comment by ajeetraina** [comment]
Did you enable API access under GCP?
Here is the log while I tried on macOS.

https://gist.github.com/ajeetraina/1634c3f3c4a9c4f1c36c421a72b616c6




On 06-May-2017 3:01 PM, "Nicolas Muller" <notifications@github.com> wrote:

Hello,

Yes I previously use the gcloud command to login into.
I use linuxkit push gcp -project mylinuxkit-166808 -bucket mygcp13000
gcpwithdocker.img.tar.gz but always FATA[0000] Unable to connect to GCP

I will test with another environment. I tested it with MacOS Sierra
(10.12.4) but I will do it again with a Linux.

Thanks for your help and the article :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/issues/1775#issuecomment-299627970>,
or mute the thread

**Comment by zepouet** [comment]
I think it is right because I can create bucket from gcloud command.

```
nicolas@macbook-pro-de-nicolas  ~/software/linuxkit/examples   master ●  gsutil mb gs://mygcp13803/
Creating gs://mygcp13803/...
```

Do you use linux or mac? I will test on Linux too. I try to upload oauth2 json file and give the path to command options `keys` but no way...

I will search again. Thanks for your help

**Comment by zepouet** [comment]
Sorry to ask but if you do an article about how to configure API it will be nice too.
If I resolve my problem, I will do it. At the moment, I don't know where is the bug :)

**Comment by ajeetraina** [comment]
@zepouet Did you try it on Linux system? It worked for me both on macOS and Linux system.
I am unable to reproduce your issue.

**Comment by ajeetraina** [comment]
Just to test if its slow connectivity issue, you can try it with small file:

For Example:

`$touch test.img.tar.gz`


```
Ajeets-MacBook-Air:examples ajeetraina$ sudo linuxkit push gcp -project synthetic-diode-161714 -bucket mygcp test.img.tar.gz 
Uploading file test.img.tar.gz to Google Storage as test.img.tar.gz
Upload Complete!
gs://mygcp/test.img.tar.gz
Creating image: test
```

This will help you troubleshoot if its actually network issue or proper permission around bucket or else.

**Comment by dave-tucker** [comment]
Note. You can also use the `linuxkit -v` for verbose mode to see where it's failing...
I am pretty sure it'll be related to your credentials.

As for documentation, I'd recommend starting with the docs that are [in-tree](https://github.com/linuxkit/linuxkit/blob/master/docs/gcp.md). The TL;DR is that you either need to supply `-keys /path/to/service-account-credentials.json` or run the magical `gcloud auth application-default login` to enable local applications to use application default credentials.

**Comment by zepouet** [comment]
Hello,

I test it on a linux and it is succesfull. Sorry if the problem is on my mac env.
I will try to investigate to have more information into trace.
Thanks @dave-tucker @ajeetraina. It rocks !
