### ISSUE TITLE
Cannot build large project with several containers

### ISSUE THREAD

**Issue by zepouet** [linuxkit/linuxkit#1819]
Hello,

I am trying to build a linux image with 5 docker images.
It is not an extrem project but just an simple application used during training (a fork about official docker voting app).The file is attached.

The problem is not with the run of the application but on the build of the linux image.

If you use an mac, you need to increase memory for docker.
If you use a linux vm, give a lot of memory. (16 Go for example).

With Mac, you have one major file with 0k
With Linux, you have files but maybe corrupted. No way to run it

I hope to run 5 containers (3 java applications + redis + postgres) to have a complete stack

**_When I do an `htop`, i see there is zip task using lot of cpus because files are large._**

File is here [computengine.yml.txt](https://github.com/linuxkit/linuxkit/files/998423/computengine.yml.txt)

For MacOSX (8 Go with xHyve)
```
moby build computengine.yml
...
...
Create outputs:
  computengine-kernel computengine-initrd.img computengine-cmdline
  computengine.img.tar.gz
 nicolas@MacBook-Pro-de-nicolas  ~/software/vertx/vertx-voting-app/linuxkit   master ●  ll
total 1630656
-rw-r--r--  1 nicolas  staff    40B 13 mai 09:07 computengine-cmdline
-rw-r--r--  1 nicolas  staff   789M 13 mai 09:07 computengine-initrd.img
-rw-r--r--  1 nicolas  staff   7,2M 13 mai 09:07 computengine-kernel
-rw-r--r--  1 nicolas  staff     0B 13 mai 09:09 computengine.img.tar.gz
-rw-r--r--  1 nicolas  staff   4,1K 12 mai 17:15 computengine.yml
```

For Linux (Ubuntu 16.04 with 16 Go)
```
moby build computengine.yml
...
...
Create outputs:
  computengine-kernel computengine-initrd.img computengine-cmdline
  computengine.img.tar.gz
root@cu03:~/vertx-voting-app/linuxkit# ll
total 1.6G
-rw-r--r-- 1 root root   40 May 13 07:19 computengine-cmdline
-rw-r--r-- 1 root root 794M May 13 07:24 computengine.img.tar.gz
-rw-r--r-- 1 root root 790M May 13 07:19 computengine-initrd.img
-rw-r--r-- 1 root root 7.2M May 13 07:19 computengine-kernel
-rw-r--r-- 1 root root 4.1K May 12 15:18 computengine.yml
```

Thanks for your help.
Best regards,

**Comment by justincormack** [comment]
All the processing takes place in memory, and the images are booted from ramdisk (and currently require around 4x as much RAM as the size of the image to boot). The memory usage for build could be improved by switching from keeping the intermediate files in memory to using streaming interfaces; this should be fairly simple but we probably won't do it until the switch to using the containerd image store is completed and various other refactorings, as it will be much simpler then. After this pretty much all the data will be in the image store so we can switch to writing that to a disk file instead of the ramdisk in some boot environments, which will solve the space usage. So there is a roadmap to making this work. In addition we will have layer sharing with the image store which will help too.

However, I would recommend making your images much smaller - it seems unlikely you need quite this much. Postgres is only a few megabyes from memory, and Java apps are unlikely to be huge either, so you almost certainly are including lots of stuff you do not need.

**Comment by zepouet** [comment]
Thanks @justincormack for your response. I reduced the java image with Alpine reference. 
Thanks to take time to explain. I wonder if __philosophy__ (sorry for my former teacher) was to include many containers at build into image or insert only one. I understand that we can put several containers but at the moment we must take care of the number of thems and weight !

So I can build them easily in Linux and MacOSX (divided by 10 with Alpine base image)

````
root@cu03:~# docker images
REPOSITORY                           TAG                         SIZE
vertxswarm/verticle-result     latest                       98.41 MB
vertxswarm/verticle-worker     latest                       98.37 MB
vertxswarm/verticle-vote       latest                       89.62 MB
postgres                       9.6-alpine                   37.71 MB
redis                          3.0.7-alpine                 2.64 MB
````
I go on !

Long life to LinuxKit 👍
