### ISSUE TITLE
Fix hyperkit runner stdio handling

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1923]
The main issue with using the hyperkit runner for tests is that stdio can't easily be redirected because  hyperkit expect a TTY.

`linuxkit.platforms.hyperkit.run_kernel` gets around this by using `expect` which makes it hard to write tests which work with different other backends.

The `script` utility also creates a fake TTY and can be used to save the output to a file.

The idea, then, is to provide a generic shell function in the test library which save the output of a command to a file (using `script` on macOS and redirect with qemu) and use that in all tests which should be run with whatever native runner exists on the platform.

**Comment by justincormack** [comment]
Can't the Go hyperkit library open a pty if stdin is not a tty?

On 28 May 2017 12:57, "Rolf Neugebauer" <notifications@github.com> wrote:

The main issue with using the hyperkit runner for tests is that stdio can't
easily be redirected because hyperkit expect a TTY.

linuxkit.platforms.hyperkit.run_kernel gets around this by using expect
which makes it hard to write tests which work with different other backends.

The script utility also creates a fake TTY and can be used to save the
output to a file.

The idea, then, is to provide a generic shell function in the test library
which save the output of a command to a file (using script on macOS and
redirect with qemu) and use that in all tests which should be run with
whatever native runner exists on the platform.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/issues/1923>, or mute the thread
