### ISSUE TITLE
projects/kubernetes run boot script fails

### ISSUE THREAD

**Issue by kairen** [linuxkit/linuxkit#2006]
I want to run `boot-master.sh` to boot a master, but I get an error as follow:
```sh
$ ./boot-master.sh
+ rm -f kube-master-disk.img
+ ../../bin/linuxkit run -cpus 2 -mem 4096 -disk-size 4096 kube-master
flag provided but not defined: -disk-size
USAGE: linuxkit run hyperkit [options] prefix

'prefix' specifies the path to the VM image.

Options:
  -cpus int
    	Number of CPUs (default 1)
  -data string
    	Metadata to pass to VM (either a path to a file or a string)
  -disk value
    	Disk config. [file=]path[,size=1G]
  -hyperkit string
    	Path to hyperkit binary (if not in default location)
  -ip string
    	IP address for the VM
  -mem int
    	Amount of memory in MB (default 1024)
  -networking string
    	Networking mode. Valid options are 'docker-for-mac', 'vpnkit[,socket-path]' and 'none'. 'docker-for-mac' connects to the network used by Docker for Mac. 'vpnkit' connects to the VPNKit socket specified. If socket-path is omitted a new VPNKit instance will be started and 'vpnkit_eth.sock' will be created in the state directory. 'none' disables networking.` (default "docker-for-mac")
  -state string
    	Path to directory to keep VM state in
  -vsock-ports string
    	List of vsock ports to forward from the guest on startup (comma separated). A unix domain socket for each port will be created in the state directory
```

This error looks like being linuxkit flag is changed.

**Comment by justincormack** [comment]
Yes sorry -disk size=200M or similar should work. If you could test and
send a PR that would be great!


On 8 Jun 2017 7:50 pm, "Kyle Bai" <notifications@github.com> wrote:

I want to run boot-master.sh to boot a master, but I get an error as follow:

$ ./boot-master.sh\+ rm -f kube-master-disk.img\+ ../../bin/linuxkit
run -cpus 2 -mem 4096 -disk-size 4096 kube-master
flag provided but not defined: -disk-size
...

This error looks like being linuxkit flag is changed. Now, the -disk-size
is already becoming too -disk.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/linuxkit/linuxkit/issues/2006>, or mute the thread

**Comment by riyazdf** [comment]
I'll put up a fix shortly
