### ISSUE TITLE
Use modules for hardware drivers

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2061]
With module loading now working, we should move some device drivers to be compiled as modules.

As a rule of a thumb, we should only compile in device which are commonly used on Hypervisors (mostly virtio and hyper-v) and move all other device drivers to be compiled as modules.

This should speed up boot times on local hypervisors where we care most about these things

**Comment by justincormack** [comment]
It would be good to measure the boot time before and after, so we get a handle on the improvement.

Many of the network options can be changed to be modular too.

**Comment by nrocco** [comment]
cc @m4rcu5

**Comment by m4rcu5** [comment]
I started doing some initial moving to modules for block device drivers and network device drivers in a branch [here](https://github.com/linuxkit/linuxkit/compare/master...m4rcu5:issue/2061)
An initial comparison against for example the Arch linux kernel configuration showed 650 drivers/modules that could be build as module instead of build-in, but I think that everything related to the network stack (ipv4/6, netfilter) could stay build-in as it is an essential part of the OS here.

**Comment by rn** [comment]
@m4rcu5 thanks for the branch. I think we want the virtio drivers and a view others you move to modules compiled in. I would initially just move the drivers for real HV into modules

**Comment by pwFoo** [comment]
I replaced the linuxkit kernel (config) with a custom one because I need desktop kernel modules. Would be great to have additional kernel modules. Maybe as a separated image with shared /lib/modules? So additional / desktop required kernel modules could be optional.

**Comment by rn** [comment]
That doesn't work as we'd have to run depmod on the combined modules and we have a RO file system

**Comment by pwFoo** [comment]
Ok, thanks for feedback, @rn
