### ISSUE TITLE
Add apk to getty and sshd containers

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2206]
These are the login containers so it is reasonable for a user to want to install new tools in them.

I tried to make this happen but ran into a problem which I'm unsure how to approach, hence this issue.

The problem I found was that `/var` is bind mounted from the host in both the `getty` and `sshd` containers which means that various `apk` state directories are missing and `apk` is very unhappy.

Presumably the answer is to do more fine grained binds into those containers but I haven't time to do that now so just synching state here. My WIP patch (based on #2205) is just:
```diff
commit 9c80b3315d20a41d11c71df84caeb8a4cb767fcd
Author: Ian Campbell <ijc@docker.com>
Date:   Fri Jul 14 12:52:56 2017 +0100

    sshd+getty: Add apk to these containers
    
    Since these are the user login containers, having the ability to add packages
    is useful (e.g. I quite often find I want strace).
    
    Signed-off-by: Ian Campbell <ijc@docker.com>

diff --git a/pkg/getty/Dockerfile b/pkg/getty/Dockerfile
index c1f26bf5..81878828 100644
--- a/pkg/getty/Dockerfile
+++ b/pkg/getty/Dockerfile
@@ -1,15 +1,17 @@
-FROM linuxkit/alpine:9bcf61f605ef0ce36cc94d59b8eac307862de6e1 AS mirror
+FROM linuxkit/alpine:3744607156e6b67e3e7d083b15be9e7722215e73 AS mirror
 
 RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
 RUN apk add --no-cache --initdb -p /out \
     alpine-baselayout \
+    apk-tools \
     busybox \
     ca-certificates \
     musl \
     tini \
     util-linux \
     && true
-RUN rm -rf /out/etc/apk /out/lib/apk /out/var/cache
+RUN mv /out/etc/apk/repositories.upstream /out/etc/apk/repositories
+
 #
 # We require a version of `setsid(1)` which supports the `-w`
 # option, which is not available in all implementations (e.g. the
diff --git a/pkg/sshd/Dockerfile b/pkg/sshd/Dockerfile
index ea724738..0ad93894 100644
--- a/pkg/sshd/Dockerfile
+++ b/pkg/sshd/Dockerfile
@@ -1,8 +1,9 @@
-FROM linuxkit/alpine:9bcf61f605ef0ce36cc94d59b8eac307862de6e1 AS mirror
+FROM linuxkit/alpine:3744607156e6b67e3e7d083b15be9e7722215e73 AS mirror
 
 RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
 RUN apk add --no-cache --initdb -p /out \
     alpine-baselayout \
+    apk-tools \
     busybox \
     ca-certificates \
     musl \
@@ -10,7 +11,7 @@ RUN apk add --no-cache --initdb -p /out \
     tini \
     util-linux \
     && true
-RUN rm -rf /out/etc/apk /out/lib/apk /out/var/cache
+RUN mv /out/etc/apk/repositories.upstream /out/etc/apk/repositories
 
 FROM scratch
 ENTRYPOINT []
```

**Comment by deitch** [comment]
The main reason `/var` is bind mounted in is because it is the read-write portion, where a lot of stuff happens. It was reasonable to assume that people would need access to that. There is nothing in these containers _per se_ that requires `/var` access. Just that the majority of login activities will require access.

But, yes, that will be a problem. 

One possibility is to keep `/var` local, and mount `/var:/hostroot/var` like we do `/etc:/hostroot/etc`. The container has its own `/var`, but you can _access_ host's `/var` like its `/etc` via `/hostroot/var`.

Cannot think of an easier way at the moment. I also don't see any significant downside either. Thoughts?

**Comment by deitch** [comment]
FYI, I would like to merge sshd and getty images, when I can find some time.

**Comment by ijc** [comment]
There are some bits of host `/var` which we might want access to from these containers, e.g. `/var/lib/containerd` or some parts `/var/run` perhaps (for `ctr` usage, although the actual socket is in `/run` so maybe not). Main reason for filing the issue rather than just fixing is I haven't got time today to fully investigate which paths might or might not be needed.

I thought I had seen chat somewhere or other (from @justincormack I suppose) about not wanting to keep `hostroot` long term, but maybe I'm misremembering that.

**Comment by deitch** [comment]
> There are some bits of host /var which we might want access to from these containers, e.g. /var/lib/containerd or some parts /var/run perhaps

Hmm, yeah, I hadn't thought that part all the way through. As you pointed out, `/var/run` is less of an issue because the socket is in `/run` (which is mounted directly). 

If we specifically need `/var/lib/containerd` or `/var/run` then we can bind mount those more explicitly.

> I thought I had seen chat somewhere or other (from @justincormack I suppose) about not wanting to keep hostroot long term

IIRC, it was not about not keeping `/hostroot/` as much as not doing a complete `/:/hostroot` map. For specific things, though, I think he was ok with it, hence `/etc:/hostroot/etc`.

So:

* explicitly mount `/var/lib/containerd:/var/lib/containerd`
* mount `/var:/hostroot/var`
* mount `/run:/run` (well, that is in already)
* leave `/var` local to the container

I think that would work. WDYT, @ijc? @justincormack ?
