### ISSUE TITLE
containerd-getty test flaky

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2229]
`containerd-getty`  test has been a bit flaky over the weekend. Redis is quite a big image to download, maybe could be replaced with a busybox/alpine test

**Comment by justincormack** [comment]
@thaJeztah we dont seem to have a flaky test label in this repo...

**Comment by thaJeztah** [comment]
hm, looks like I don't have permissions in this repository 😅

**Comment by justincormack** [comment]
Hmm, moby/moby no longer has one either

**Comment by ijc** [comment]
Switching to a smaller image download would be fine but I don't know if it would be sufficient to call this issue closed, the tests pull a lot of other stuff (multiple kernel images for example) which must be the same order of magnitude in terms of download size, so if that was the issue I would expect those to suffer issues too.

#2224 turned out to be https://github.com/linuxkit/rtf/issues/23, do we have an other examples of a failure so I can have a look at whether it is indeed the size of the download or if something else is going on?

**Comment by justincormack** [comment]
This is a download from hub. There is no reason to use redis, all we are doing is testing if we can download and run a container. The output changed over the weekend too as we dont pin the image. Using hello world or something makes much more sense.

**Comment by ijc** [comment]
The `redis` image had some interesting property or other, but I can't remember what it was! So we may as well make the change, and ack to pinning.

**Comment by ijc** [comment]
> we may as well make

By which I mean "I am making...", PR shortly.
