### ISSUE TITLE
Add scaleway support

### ISSUE THREAD

**Issue by yangm97** [linuxkit/linuxkit#2487]
Scaleway currently supports launching instances using docker images, so I think there shouldn’t be much needed to make this work.

**Comment by rn** [comment]
we currently have no one working on this, but happy to accept patches :)

**Comment by justincormack** [comment]
Is it possible yet to use custom kernel images? I saw it was possible with `kexec` but that makes for a custom boot process compared to other platforms, which is a bit more complex to implement.

**Comment by Sh4d1** [comment]
Hey!

Apparently [you can](https://github.com/scaleway/kernel-tools/blob/master/README.md#how-to-build-a-custom-kernel-module).
I'm very interested in this feature, what can I do to help ?

Cheers,

Patrik

**Comment by justincormack** [comment]
Its very confusing, according to https://github.com/BobVul/Custom-Kernel-Launcher-for-Scaleway it is still based on `kexec`. A `kexec` setup should work.

Also that page is for the C1 server, which is 32 bit arm for which we dont yet have support. I don't know which model you are looking at on Scaleway, they have a mix of KVM and bare metal which will probably have different setups.

**Comment by Sh4d1** [comment]
Indeed, and the documentation is kind of spread everywhere. I'm currently using VC1S which is on KVM, but bare metal would also work. 

I'll try to look into it when I have some time. 

I also need to check their docker images, they only use ubuntu as base image, have to see if it is working with another base image. Would be easier if they supported iso images haha

**Comment by Sh4d1** [comment]
@justincormack I think now it is officially supported: https://blog.online.net/2018/04/19/scaleway-feature-improvements-custom-kernel-security-group-live-reload-imagehub-packer/

Any suggestions on how to proceed now?

**Comment by justincormack** [comment]
Hmm, would need to try it out. It looks like it may still be very inconvenient from that brief doc, as you apparently have to install a distro first to then modify the kernel?

**Comment by Sh4d1** [comment]
Okay so I managed to boot linuxkit from ipxe. However when I reboot the instance, it does not reboot correctly. Just like Packet if I'm not wrong? 

So I guess it could be implemented as Packet, but with no persistent storage.

Or if we look into the local boot options, it would be needed to spin up a temporary instance in order to copy the rootfs, kernel and initrd, but if it works, I guess we would have persistent storage. 

So is it possible to implement both features? And let the user choose when doing a `linuxkit run`. Or is it better to just focus on one?

**Comment by Sh4d1** [comment]
I also managed to create a Scaleway image running Linuxkit. But yeah, I had to create another instance, change the root volume in the cmdline, build an efi-iso, copy to the instance, dd on an additional volume, snapshot the volume, and create an image from this snapshot. 

Additionally, I have to manually signal Scaleway that the instance has started (it reboots after a few minuts otherwise). 

I'll start to work on an go implementation during the week. I was thinking of:
* `linuxkit push` to create the image, so using scaleway's go api to create an instance, copy the iso, dd on onether volume, create the snapshot and then the image
* `linuxkit run` to run this created image

**Comment by Sh4d1** [comment]
@justincormack @rn I finished (kind of) the `linuxkit push scaleway` with #3018 

Any thoughts?

**Comment by Sh4d1** [comment]
FYI, this is my branch if you want to check/try it :) https://github.com/Sh4d1/linuxkit/tree/scaleway_provider

**Comment by yangm97** [comment]
@Sh4d1 nice work on the current implementation!

But now that scaleway provides a S3 compatible storage service, I wonder if the push process could be simplified by uploading the initrd etc. into a bucket. By extension, that would add support for baremetal servers, which do not support "local" kernel images, only booting from an URL.
