### ISSUE TITLE
new linuxkit pkg push throws non-fatal .docker/config.json warning

### ISSUE THREAD

**Issue by eyz** [linuxkit/linuxkit#2590]
**Description**
```
cat: /home/isaac.rodman/.docker/config.jsonerror: syntax error, unexpected QQSTRING_START, expecting IDENT
.auths."https://index.docker.io/v1/".auth
       ^
1 compile error
: No such file or directory
```

**Steps to reproduce the issue:**
- `linuxkit pkg push --force -disable-content-trust -org MYREGISTRY:5000 -release "${RELEASE_TAG}" my-swap` is building, tagging, and pushing as expected
- this produces the error

**Describe the results you received:**
- received above warning

**Describe the results you expected:**
- expecting no warning

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ijc** [comment]
Thanks for the report. A few thoughts/notes to self/.:

* I don't think this is due to the switch to `linuxkit pkg`, previously a `make push` would have ended up in the same error
* The issue is that the script is expecting you to be logged into docker hub and hence expecting that `/home/isaac.rodman/.docker/config.json` exists and contains specific keys. If you are pushing to a private registry this may not be the case that you are logged into the hub.
* I notice that if you were pushing to an _authenticated_ private registry then the script would be trying to extract the creds for the wrong registry. 
* #2584 is somewhat related (in that rewritting would be a good time to sort all the above).

**Comment by eyz** [comment]
This was just a quick issue, so let me know if you need more detail or testing on my part.

**Comment by rn** [comment]
@ijc are you planning to look into this? I had tentatively marked this for the 0.2 milestone, but now removed it since I plan to cut it tomorrow and likely needs most of the day for it

**Comment by eyz** [comment]
I don't recall seeing this anymore. Checking.

**Comment by ijc** [comment]
@rn I have no immediate plans to look in to it, but I don't think it should block a 0.2 release.

**Comment by eyz** [comment]
I'm not having issues pushing to my private registry on LinuxKit 0.6. Closing
