### ISSUE TITLE
metadata: tree is limited to only 2 levels

### ISSUE THREAD

**Issue by guillaumerose** [linuxkit/linuxkit#2641]
**Description**

The json metadata represents a disk. A disk can have more than 2 levels of depth.

**Steps to reproduce the issue:**

Mount a json file like this: 

```
{
  "etc": {
    "ssl": {
      "certs": {
        "ca-certificates.crt": {
          "perm": "0644",
          "content": "some content"
        }
      }
    }
  }
}
```

**Describe the results you received:**

Directory etc is empty

**Describe the results you expected:**

The tree described in the json exists.

**Comment by ijc** [comment]
I think this behaves as `docs/metadata.md` describes:
> different keys cause directories to be created and the directories are populated with files.

although it could more clearly indicate that this isn't recursive.

Since this all ends up under `/var/config` I'm not sure that the ability to create e.g. `/var/config/etc/ssl/certs/ca-certificates.crt` is all that useful, it doesn't really need to mirror the layout from `/`.

In this case I'd probably just arrange for `/var/config/certs/ca-certificates.crt`. Maybe `foo-certs` if you need some namespacing for some reason. In `projects/kubernetes` I've mostly been using the name of the component which consumes the file as the directory name, e.g. `/var/config/kubeadm`, `/var/config/kubelet` etc.

I don't think we've reached the limits of what the existing mostly flat structure can give us, maybe we should just fix the doc to be clearer?

If we were to extend to nesting, then I don't think it would be as simple as the example given, since you would need a way to support ownership and perms, which implies a directory is actually a json object with various fields including a `contents` one or something, rather than the simple nested maps the example shows.

Lastly, given the constraints of go's json parser I'm not sure how easy it would be to support nesting (although clearly that shouldn't be a blocker if we think we really need it).

**Comment by rn** [comment]
I agree with @ijc: The hierarchy under `/var/config` does not need to mirror the hierarchy in `/`. The idea behind the two level hierarchy was to just group files my topic/package and that that would be sufficient.

Do you have a use case in mind where it is not sufficient (or would be extremely ugly/awkward)?

**Comment by guillaumerose** [comment]
Yes, sadly, there is a use case. In Docker for Mac, we copy client certificates located in ~/.docker/certs.d inside the VM. 

The structure is like this :
```
    /etc/docker/certs.d/        <-- Certificate directory
    └── localhost:5000          <-- Hostname:port
       ├── client.cert          <-- Client certificate
       ├── client.key           <-- Client key
       └── ca.crt               <-- Certificate authority that signed
                                    the registry certificate
```

See https://docs.docker.com/engine/security/certificates/#creating-the-client-certificates

**Comment by ijc** [comment]
Unless you have multiple such bundles you could still structure this as:
```
/var/config/localhost-certs
 ├── client.cert          <-- Client certificate
 ├── client.key           <-- Client key
 └── ca.crt               <-- Certificate authority that signed
                              the registry certificate
```

**Comment by guillaumerose** [comment]
That's the problem, you can have multiple hosts

**Comment by justincormack** [comment]
I didnt think that we use `/etc/docker/certs.d` any more in d4mac, indeed the whole setup has been deprecated for quite some time I thought. We just have a single host cert file. I can't see any way to setup `/etc/docker/certs.d` in the UI any more.

**Comment by guillaumerose** [comment]
Docker for Mac users reported the problem : https://github.com/docker/for-mac/issues/2201
