### ISSUE TITLE
Building for Raspberry Pi 3

### ISSUE THREAD

**Issue by ns-cweber** [linuxkit/linuxkit#3022]
Hi, it seems that we can't build an artifact for RPI3 except from an ARM64 machine. This is quite limiting since such machines are rare except for RPI3, and most RPI OSes are 32-bit (1GB of RAM and all that). Do I just need to install a 64-bit OS on an RPI in order to build images for RPI3? Perhaps the linuxkit/RPI3 docs could be updated to prescribe a solution?

**Comment by justincormack** [comment]
That is currently a Docker limitation, where you cannot easily pull container images for different architectures. We are planning to switch to containerd at some point, and this issue should be fixed upstream see https://github.com/moby/moby/issues/36552. You can get access to arm64 machines from Scaleway and Packet.net.

**Comment by rn** [comment]
Yes, unfortunately at the moment you need a `arm64` machine to build LinuxKit `arm64` machines. The same is true for `s390x`. This is because we can't pull images for "foreign" architectures.

I'm using  a `arm64` server on packet.net for building but you maybe be able to run things in qemu with aarch64 (haven't tried so don't know how slow this might be) or a 64bit distro on a RPi3 (there are some out there, forgot which ones)

**Comment by ns-cweber** [comment]
@justincormack @rn Thanks for the prompt, informative replies!
