### ISSUE TITLE
Question: Monitoring linuxkit 

### ISSUE THREAD

**Issue by scriptjs** [linuxkit/linuxkit#3083]
Can your provide advice about what could be used to monitor the health of a linuxkit host and provide alerts. Many thanks.

**Comment by hairyhenderson** [comment]
@scriptjs An example of adding the Prometheus node-exporter is available here: https://github.com/linuxkit/linuxkit/blob/master/examples/node_exporter.yml

Personally I monitor all my hosts (LinuxKit-based and otherwise) with Prometheus and node-exporter, and configure Prometheus to alert based on various conditions. IMO there's nothing particular special about LinuxKit that would change the way you'd monitor it - do it the same way you'd do it for any other Linux host...

**Comment by scriptjs** [comment]
@hairyhenderson Thank you.
