### ISSUE TITLE
Improve linuxkit pkg build to be able to use external sources

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3108]
Currently, `linuxkit pkg build` assumes that all the sources for a package are in the package directory. The hash for the package is the git tree hash of the package directory. In some cases this leads to duplication of code, e.g., for go vendoring.

In a conversation with @ijc and @justincormack we discussed to potential extension to `linuxkit pkg build` to also consider external sources. Here is a more detailed proposal:

- Add a new `sources` entry to `build.yml` which takes a list of `<src>:<dst>` strings, where `<src>` and `<dst>` are directories and `<src>` should be under git source control.
- During build the <src> directory is copied to <dst> in the build context where it will be available to the `Dockerfile`.
- To compute the package hash `linuxkit pkg` will use the git tree hash of the package directory and XOR it with the git tree hash of all the `<src>` directories.

**Comment by ijc** [comment]
#2586 is relevant here, #2583 maybe a bit too.

I wouldn't XOR, else you can't include the same code at two different points, plus the semantics of XORing hashes together is not something I want to think very hard about. I think I would construct a document of some sort with the input hashes in (perhaps just a json array) and take the hash of that. Since ideally the input hashes would be recoverable from the image too you could stash the same array in a label.

I think you can avoid a literal copy by feeding `docker build` a series of constructed tarballs with things in the right places...

**Comment by justincormack** [comment]
Just doing sha1("sha1 sha1") or something should be fine for this purpose (of course if git switches its hashes to sha256 one of these years we might need to change it).

**Comment by deitch** [comment]
I am trying to wrap my head around the use. Right now, I can do `lkt pkg build pkg/foo` to build `foo`. 

Is the only reason for this to avoid duplicating `pkg/foo/vendor/` on `pkg/bar/vendor/`?

**Comment by deitch** [comment]
Hmm.... is that a bug or a feature, when each package is self-sustained?

**Comment by rn** [comment]
For the packages in LinuxKit this is not that much of an issue, but for more complex setups, like for example we have in Docker Desktop where versions need to be synchronised across different build environments it becomes an issue.

**Comment by deitch** [comment]
Got it. 

Sometimes it feels like every project ever made rebuilds packaging somehow. :-)
