### ISSUE TITLE
Add utility to VM

### ISSUE THREAD

**Issue by montao** [linuxkit/linuxkit#3220]
**Description**
I am a beginner with LinuxKit. I search for the information of how to achieve the equivalent of `apk add...` in a YAML file. If I run LinuxKit, I can add git with `apk add git` but I want to do it in the YAML file. I tried adding git as a service:
```
  - name: git
    image: alpine/git
    command:
      - git
```
That builds and runs but then I am unable to run the git service:

```

(ns: sshd) linuxkit-00155d21011e:~# ctr -n services.linuxkit task ls
TASK      PID    STATUS
dhcpcd    649    RUNNING
getty     707    RUNNING
git       775    STOPPED
rngd      861    RUNNING
sshd      906    RUNNING
(ns: sshd) linuxkit-00155d21011e:~# ctr -n services.linuxkit task start git
ctr: mkdir /run/containerd/io.containerd.runtime.v1.linux/services.linuxkit/git: file exists: unknown
(ns: sshd) linuxkit-00155d21011e:~#
```

**Steps to reproduce the issue:**
Try to install user programs. 

**Describe the results you received:**

```
(ns: getty) linuxkit-00155d210111:~# git
git
-sh: git: not found
(ns: getty) linuxkit-00155d210111:~# runc exec git
runc exec git
exec failed: container "git" does not exist
(ns: getty) linuxkit-00155d210111:~#
```

**Describe the results you expected:**

```

(ns: getty) linuxkit-00155d210111:~# git
git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
@montao Linuxkit is not really designed for general use. The idea is to have all the tools needed for specific task baked into the image itself. If you need `git` you should include it into your image. LinuxKit is also designed along the ideal of immutable infrastructure, ie we try to not install packages from the network once booted. If you need to have a package, bake it into the image, if you need to update, build a new image and reboot it. The default root filesystem is also read-only and/or a ramdisk so that makes adding new packages harder as well.

The LinuxKit "package" are just normal docker images. So you can build your own image and add it instead of `- name: ...`. For git, you can also build your own, e.g., by modifying the ssh package.

If you want

**Comment by montao** [comment]
@rn I understand.

**Comment by rn** [comment]
@montao do you have a specific use case in mind. LinuxKit is a bit unusual so some use case might not be a good match, but happy to discuss. Might be best on the slack channel, but GH issues work too.
