### ISSUE TITLE
make kconfig doesn't work as per manual

### ISSUE THREAD

**Issue by alekslitvinenk** [linuxkit/linuxkit#3333]
**Description**
If follow the manual to make custom kernel builds, the error pops up:
`make: *** No rule to make target 'sources' needed by kconfig`

**Steps to reproduce the issue:**
1) Navigate to `kernel` directory
2) Type in shell the following command: `make kconfig`
3) Observe the error : `make: *** No rule to make target 'sources' needed by kconfig`

**Describe the results you received:**
`make: *** No rule to make target 'sources' needed by kconfig` pops up. 

**Describe the results you expected:**
```
Successfully built <****>
Successfully tagged linuxkit/kconfig:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**
It seems like if prior `make kconfig` create an empty folder `sources`, it solves the issue.
Most likely the manual has to be updated

**Comment by tjfontaine** [comment]
I can confirm this happens, the local workaround I use is to `mkdir kernel/sources`, I'm not sure what if anything is supposed to be there (presumably some form of caching of the source balls) but the rest of the builds for the kernel work (`kconfig` and `build_`) once that directory is there.

**Comment by rn** [comment]
yeah, I noticed this the other day as well. The `mkdir kernel/sources` fixed it for me too. The `sources` directory was indeed at some point intended to have a local cache of kernel source tar ball. But, I haven't used it in a while since my internet is fast enough and most time in the kernel compile is now spent elsewhere. I'm tempted to remove the local cache

**Comment by alekslitvinenk** [comment]
Awesome!
