### ISSUE TITLE
bug in `mkimage-raw-efi` choking on kernel file and directory

### ISSUE THREAD

**Issue by gaahrdner** [linuxkit/linuxkit#3340]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Unable to build a `raw-efi` image.

**Steps to reproduce the issue:**

1. Reproducible with the `linux.yml` example.
2. Build the example with a format of `tar`
3. Attempt to convert the tar ball to a `raw-efi` image.

**Describe the results you received:**

```
 2019-05-01 16:35:01 ⌚  C02WW2ZCHTDD in ~/Code/teamcity-agent-kubevirt
± |master U:4 ?:5 ✗| → cat vm/teamcity-agent-vm.tar | docker run -i -e DEBUG=true linuxkit/mkimage-raw-efi:2d1a0e6e67c967bd4d5a859eb9044571f6844577
+ IMGFILE=//disk.img
+ exec
+ ESP_FILE=//boot.img
+ uname -m
+ ARCH=x86_64
+ BOOTFILE=BOOTX64.EFI
+ LINUX_ENTRY=linuxefi
+ INITRD_ENTRY=initrdefi
+ mkdir -p /tmp/efi
+ cd /tmp/efi
+ '[' -t 0 ]
+ bsdtar xzf -
+ find . -name '*.img'
+ INITRD=
+ find . -name kernel
+ KERNEL='./lib/modules/4.19.37-linuxkit/kernel
./boot/kernel
./containers/services/teamcity-agent/lower/etc/kernel'
+ find . -name cmdline
+ CMDLINE_FILE=./boot/cmdline
+ cat ./boot/cmdline
+ CMDLINE='console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0 pti=off'
+ cat /proc/sys/kernel/random/uuid
+ PARTUUID=17afb7ef-d237-4d6f-8099-d33cf7ccf1e6
+ cp /usr/local/share/BOOTX64.EFI .
+ mkdir -p EFI/BOOT
+ cat
+ stat -c '%s' './lib/modules/4.19.37-linuxkit/kernel
./boot/kernel
./containers/services/teamcity-agent/lower/etc/kernel'
stat: can't stat './lib/modules/4.19.37-linuxkit/kernel
./boot/kernel
./containers/services/teamcity-agent/lower/etc/kernel': No such file or directory
+ KERNEL_FILE_SIZE=
```

**Describe the results you expected:**

No error and an `img` file.

**Additional information you deem important (e.g. issue happens only occasionally):**

This will also effect:

```
mkimage-dynamic-vhd
mkimage-gcp
mkimage-qcow2-efi
mkimage-raw-bios
mkimage-raw-efi
mkimage-vhd
mkimage-vmdk
```

cc @deitch

**Comment by deitch** [comment]
This is due to the script that tries to find the kernel as:

```sh
KERNEL="$(find . -name kernel)"
```

Thus assuming that it would find only one file or directory named `kernel`, and that it would be _the_ kernel. Beginning with some revision, there also is a directory named `kernel` in `/lib/modules/`.

The easy fix would be `find . -type f -name kernel`, but I am wondering if we shouldn't be concerned there could be other files somewhere in the image named `kernel`? Should we be a bit smarter about it at this point and perhaps do `find /boot -type f -name kernel`? Maybe something else?

Thoughts @rn @rvs @ijc ?

**Comment by deitch** [comment]
Moving discussion over to #3341
