### ISSUE TITLE
Adding hostapd and dnsmasq in tools/alpine

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3384]
Hi, 
I am trying to add  two packages to the alpine/tools/packages and corresponding version files. How do I get the new hash of the alpine image that is at the top of the version file? I tried running make in the tools/alpine directory to produce the new image, but I get an error. 
I added the hostapd-2.8-r0 and dnsmasq-2.80-r3 packages to the version files.

Thank you,
Diana

**Comment by rn** [comment]
in order to add packages, you need to add them to the `packages` file. Then, when you run `make` it will create a new package and will update the `versions` files.

Adding packages to `tool/alpine` is not quite straight forward esp if you want to support multiple architectures. I'm not sure we want to add the `hostapd` and `dnsmasqd` alpine packages to the official base of linuxkit. you may be better off find other ways create a linuxkit package containing them...but we'd need to know what you are trying to do

**Comment by dapopescu** [comment]
I would like to make the Raspberry Pi into a wireless access point. 
I have been trying to make a package, but when I try to install these packages into the container/service by having into the Dockerfile 
apk add --no-cache dnsmasq hostapd
I get 
dnsmasq (missing) ERROR: unsatisfiable constraints: required by: world[dnsmasq] ...

**Comment by rn** [comment]
To start, I would not use the alpine base for trying to set this up. I would just a `FROM alpine:<version>` and then whatever `apk` stuff you need to get the binaries. 

second, you would need a different kernel. The default Linuxkit kernel has no WiFi support. Also the wifi on the raspberry Pi has is odd, IIRC, so that would be another hurdle.

**Comment by dapopescu** [comment]
Thank you. I am running into different errors now.

```
Step 1/11 : FROM alpine:3.9
 ---> ce544de9ee2c
Step 2/11 : RUN apk update &&     apk add --no-cache dnsmasq hostapd
 ---> Running in 2809bfcf32ef
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
2 errors; 14 distinct packages available
The command '/bin/sh -c apk update &&     apk add --no-cache dnsmasq hostapd' returned a non-zero code: 2
exit status 2
```
If I try the same instructions in ```docker run -ti alpine:3.9``` it works and I can install the two packages.

As for the LinuxKit kernel not having WiFi enabled, I am aware of that, thank you.

**Comment by rn** [comment]
do you have networking enabled in `build.yml`? default is off

**Comment by dapopescu** [comment]
Thank you, this was the problem. 
I am now trying to run the two, ```hostapd``` and ```dnsmasq``` (and ```dhcpcd```) in the same container. Since I am starting all these three as daemons, I believe the container finishes after executing the CMD listed in the Dockerfile (I ran ``ctr -n services.linuxkit t ls``` and I did not see it running). I did not see any errors in /var/log for this service.
From what I have seen in the ```sshd```, ```openntp``` and ```dhcpcd``` packages, these are run in the foreground.  Would it be advisable then to have them as separate containers and running in the foreground? But then will their configurations be accessible from each other,  and will their effects be seen on the network configuration everywhere?

**Comment by rn** [comment]
Running them in separate containers will require careful config of network namespaces. The WireGuard sample might give some ideas. If you want to share config files you’d probably also need to create bind mounts

**Comment by dapopescu** [comment]
Ok, but is there any particular reason for why the packages I mentioned run sshd, ntp, dhcpcd in the foreground?

**Comment by rn** [comment]
not sure, but I think services don't wait for daemonised processes to exit and then get restarted
