### ISSUE TITLE
Kernel panic error due to insufficient RAM - RPi3

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3414]
Hi,
Similarly to the previous issues (https://github.com/linuxkit/linuxkit/issues/2980, https://github.com/linuxkit/linuxkit/issues/2713), I get a kernel panic error due to insufficient RAM. However, none of the solutions seem to be suitable for my case, where I boot LinuxKit on a Raspberry Pi, for which I built the image using the -format rpi3 option. Any ideas on how to increase the RAM in my case?

Thank you,
Diana

**Comment by rn** [comment]
You can't really increase the RAM. ON RPi3 we still boot with the rootfs in a RAM disk so if your root filesystem is too large this will fail. Can you make it smaller? Otherwise the only other option is to get the root filesystem onto a partition on the flash card, maybe as squashfs but that requires development work.

**Comment by dapopescu** [comment]
Thank you for your answer. I was hoping there is something similar to "linuxkit run -mem=..." option described as solution for the previous issues. 
When I run "df -h" on the RPi, I see that the root filesystem has  ~512MB, isn't it possible to increase this size?

**Comment by dapopescu** [comment]
Ah, my bad, I thought the RPi 3b+ has 4GB of available RAM, and that I am somehow capped because I was running LinuxKit, but only RPi4 has 4GB.

**Comment by rn** [comment]
Closing. This is expected behaviour with initrd's exceeding the available RAM.
