### ISSUE TITLE
The metadata package with cdrom device filtering

### ISSUE THREAD

**Issue by giggsoff** [linuxkit/linuxkit#3506]
**Description**

After fix in #3501 the metadata package with cdrom provider works well with /dev/sr[0-9]* devices. But as described in [Cloud-Init NoCloud Source](https://github.com/canonical/cloud-init/blob/master/doc/rtd/topics/datasources/nocloud.rst):

> You can provide meta-data and user-data to a local vm boot via files on a vfat or iso9660 filesystem. The filesystem volume label must be cidata or CIDATA.

**Received result:**
Device filter by path (/dev/sr[0-9]*)
https://github.com/linuxkit/linuxkit/blob/cab95cfc515838bbb79fea2169a33048877876cc/pkg/metadata/provider_cdrom.go#L14-L16

**Expected result:**
Filtering by filesystem volume label (cidata or CIDATA)

**Comment by deitch** [comment]
I don't see any reason why we could not search for devices with the volume label in addition to standard cdrom devices.

**Comment by deitch** [comment]
In order to do this correctly, we would need to be able to find the filesystem with the label `cidata` or `CIDATA`. I dug into how `lsblk` does it, and pretty much it reads the raw bytes of the filesystem. That isn't realistic for us to implement here in `pkg/metadata` (although it might be sane to extend it in diskfs), so we need to use`lsblk`. Those aren't in this disk image, because we make it [from scratch](https://github.com/linuxkit/linuxkit/blob/master/pkg/metadata/Dockerfile#L13-L18).

I see a few roads forward:

* extend go-diskfs to support returning labels and roll it in - will take some time
* add `lsblk` to the scratch image, which should work if we include the library dependencies

**Comment by deitch** [comment]
Like to get some insight from the other maintainers here.

**Comment by deitch** [comment]
I successfully for go-diskfs to support reading labels. Will add it in here.
