### ISSUE TITLE
Inconsistency with dirty flag

### ISSUE THREAD

**Issue by giggsoff** [linuxkit/linuxkit#3817]
**Description**

In case of dirty flag set (with uncommitted changes), I am forced to use `force` flag for pkg build. Without that flag we will not rebuild the package in case of consecutive edits.

**Steps to reproduce the issue:**

1. Modify something in package source (for example in `pkg/acpid/Dockerfile`). Do not commit changes.
2. Build package (for example `linuxkit pkg build pkg/acpid`). It will ends with build log and tag with dirty suffix.
3. Modify something in package source again (in the same package as in step 1). Do not commit changes.
4. Build package again (for example `linuxkit pkg build pkg/acpid`). It will ends with `found in local cache, not pulling` and `found or pulled`, no build log.

**Describe the results you received:**

I want to have possibility to check my potentially uncommitted changes in package, i.e. to rebuild packages with consecutive uncommitted changes.

**Describe the results you expected:**

On step 4 I cannot see build log, which is not expected after edits on step 3.

**Comment by deitch** [comment]
The current logic is:

1. Create a tag using `git ls-tree HEAD pkgdir/` to get the hash
2. If the git dir is "dirty" (unstaged or uncommitted changes), then append `-dirty`.

The issue occurs because, if you change a file without commits, then the `ls-tree` hash is unchanged, and `dirty` remains the same.

The easiest solution to this would be to have a tag that changes based on file contents when dirty. E.g.:

* `acbdefg11111` - clean
* `abcdefg11111-dirty-65ffbc3` - dirty

Where the tag is made up of: `<ls-tree>-dirty-<content hash>`

* `ls-tree` as now
* `"dirty"` as now
* `<content hash>` - provided by `for file in $(git ls-files pkgdir/); do cat $file | sha256sum; done | sha256sum`

The above should be done via native go with a tree walker, but the idea is the same.

Want to give a PR for that or something similar @giggsoff ?

**Comment by giggsoff** [comment]
Make sense, thank you. Will try to implement this logic.
