### ISSUE TITLE
Docker hub binfmt tagging is.. awkward?

### ISSUE THREAD

**Issue by wleese** [linuxkit/linuxkit#4019]
**Description**

Looking at the tags at https://hub.docker.com/r/linuxkit/binfmt/tags and comparing them with releases https://github.com/linuxkit/linuxkit/releases, doesn't show a pattern.

This makes it very hard to rely on to get the most up-to-date release of e.g. the binfmt container.

**Steps to reproduce the issue:**

**Describe the results you received:**

Had to rely on a SHA, which I knew pointed to the latest 1.0.x release, rather than pointing to 1.0.1 directly.

**Describe the results you expected:**

I'd expect every linuxkit release to have a tagged container on docker hub.

**Comment by deitch** [comment]
That is because they aren't the same thing. Each _linuxkit_ release (as referenced in https://github.com/linuxkit/linuxkit/releases) is a release of the binary `linuxkit`. That is distinct from the releases of _packages_, which can follow their own pattern. 

To be fair, we didn't have a consistent pattern and system for that for a while. Only last week, we put in place a tagging system for packages, so tags `vX.Y.X` continue to generate `linuxkit` (the binary) releases, while `pkg-vX.Y.Z` now generate package releases. As a result of that, packages `v1.0.0` was just released last week.

**Comment by wleese** [comment]
Thanks for the explanation!
