### ISSUE TITLE
remote usb

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#609]
See http://usbip.sourceforge.net/ and https://kernelnewbies.org/Linux_4.7#head-b998aa95aff18633d421b139478371d2759bdeb4 - should be able to remote USB devices from the Mac or Windows in theory...

**Comment by beriberikix** [comment]
Bumping a rather old thread :) Yes, and in practice you can! The runtimes need to include the appropriate kernel module so that it can be made available to the guest container. I've done experiments USB/IP on a Linux host successfully and non-container runtimes (vanilla QEMU) on Windows and macOS. It's also worth noting that Windows official solution for [WSL2](https://learn.microsoft.com/en-us/windows/wsl/connect-usb) is USB/IP.

**Comment by beriberikix** [comment]
@justincormack Due to improvements in WSL2, I can now access USB devices from a Windows host using USB/IP ([screenshot](https://twitter.com/beriberikix/status/1746373781273383253).) This doesn't apply to macOS - would you consider enabling the kernel module?

**Comment by beriberikix** [comment]
And now we can use it in more places :) https://blog.golioth.io/usb-docker-windows-macos/
