### ISSUE TITLE
better way to manage kernel config

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#635]
Want to specify the config options that actually matter (versioned by kernel version perhaps) and then generate the others from dependencies.

Currently a kernel upgrade means a messy diff, and it is easy to not do oldconfig too.

**Comment by justincormack** [comment]
Another option is to manage like Android does see https://source.android.com/devices/tech/config/kernel with sorted sets of options https://android.googlesource.com/kernel/common/+/android-4.9/kernel/configs/android-base.config

**Comment by tych0** [comment]
Hi guys, what about something like the following:

* kernel_config.base - everything that isn't arch or version specific
  * e.g. CONFIG_NET, more detailed as we want to turn options on and off
* kernel_config.x86 - stuff that's arch (but not version) specific
  * e.g. X86_64, X86, all implied ARCH_* settings (and friends)
* kernel_config.4.9.x - stuff that's === 4.9.x specific
  * optional
* kernel_config.x86.4.9.x - stuff that's arch specific to 4.9.x
  * optional

When building a kernel, we'd cat kernel_config.base kernel_config.arch 
kernel_config.{versions <= your specified version} kernel_config.arch.{versions 
<= your specified version} all together and do old(def?)config, and use that as 
the result.

When we drop support for an old version, we can just take kernel_config.4.4.x 
and put it in kernel_config.base (similar with the .arch one).

For features (e.g. a .hardened config) or something, we'll need something 
slightly more intelligent than cat, since the features might overlap. I think 
it should be enough to make the e.g. .hardened config /replace/ all options 
that are specified in the base config, so we cat the configs together as above,
and then replace everything that is specified in .hardened.

Finally, it would be nice to be able to optionally include projects, which 
could use the same replacement strategy, I think. You'd give the tool a yaml 
file (or something) which says "I want selinux and wireguard, but not 
landlock", and it would add the patches, add the kernel config, and the 
userspace tools necessary. This would involve changing the format of the 
projects/ directly slightly, but I think it would be nice to have. In any case, 
it's not necessary for the stuff above.

**Comment by justincormack** [comment]
I would generally be keen on doing something close to Debian or Android, but it may not work for us. I would suggest doing a prototype in `projects/hardened` or `projects/kernelconfig` and we can look at it as its the detail of how manageable it is eg how we handle adding and removing options for different versions and how easy it is to see what happens over time (eg diffs and PRs) that will make the difference.

**Comment by tych0** [comment]
On Thu, May 04, 2017 at 02:43:28AM -0700, Justin Cormack wrote:
> I would generally be keen on doing something close to Debian or Android, but it may not work for us. I would suggest doing a prototype in `projects/hardened` or `projects/kernelconfig` and we can look at it as its the detail of how manageable it is eg how we handle adding and removing options for different versions and how easy it is to see what happens over time (eg diffs and PRs) that will make the difference.

Ok, my understanding of android is basically just sets of config files
with options sorted alphabetically. When I looked at debian, it looked
like they had fancier tooling to merge configs. Is there something
specific here that I'm missing?

Happy to do an implementation for projects/.

**Comment by justincormack** [comment]
Yeah the Android sorted thing (a) is easier to diff and (b) does not have the negative options, ie the commented out lines. I forget how they handle multi arch, I thought they divided it up into arch pieces too?

I think doing a prototype will be the best way to see what the issues are anyway...

**Comment by tych0** [comment]
Yes, one problem with the negative configs is what to do about decisions where we want to disable stuff that's enabled by default (e.g. CONFIG_USELIB). We could simply `yes n | make oldconfig`, but perhaps there is a better option.

Perhaps we just list everything that's different than defconfig, sorted alphabetically?

**Comment by rn** [comment]
I recently committed a bunch of changes relevant to this issue:
- [This commit](https://github.com/linuxkit/linuxkit/pull/2440/commits/9362de0adb395a79a529e97d42f4653f8088c901) makes sure that the `.config` generated by `make defconfig/oldconfig` is identical to the one checked in. This should fail if there are any new/renamed config options etc.
- [This commit](https://github.com/linuxkit/linuxkit/pull/2445/commits/c3b9972b3208ac6f484a3e496e5e64dc0fbe3b3d) adds a utility to split the bunch of config files into common parts and could be used iteratively to split up the config into common, kernel version, and arch common.
- [This commit](https://github.com/linuxkit/linuxkit/pull/2445/commits/ba2e6a5bb888ddec4a9abaf4907369722156dba9) adds a container image to work with kernel configurations.

I've also taken a look at the Debian tooling. Debian splits kernel config files into common, arch, and feature set (like [here](https://anonscm.debian.org/cgit/kernel/linux.git/tree/debian/config)) and then has different branches in that repository for different kernels. There is some nice tooling [here](https://anonscm.debian.org/cgit/kernel/kernel-team.git/tree/utils/kconfigeditor2) which helps managing the split configuration. The tooling understands to some extend the kernel config system and parses the all the `Kconfig` files. The tooling does things like prettifying the split config files (group the options into sections, one per `Kconfig` file) and I believe can also be used to check that options did not change etc.

However, we can't directly use the Debian tooling as both the directory layout as well as concepts, such as feature set) are pretty hard coded in quite a few files and this would need to be adjusted. We'd further need to make adjustments to support different kernel versions. Doable, but work...

The alternative is kinda a half way, which is just to have split config files like @tych0 PR #2445. While this is nice to share significant parts of the config, it makes it harder to modify config files (they are not grouped anymore) and it makes it harder to check if there were any changes. in #2445 there is a script which tries to catch such changes.

After having played a bit with the above while trying to harmonise the config files across 4.4/4.9 and x86/arm64 I'm now leaning towards having the full config files checked in as currently is. This makes it easy to edit (`vi`, `emacs`, `make menuconfig`) and easy to check that nothing unexpected change (`diff`). It makes it a little tedious to update the config, ie when adding a new driver or some such, but so far that seems to have been rare.

So, I propose to close this issue (and #2445), but it would be good to get opinions from others first?
/cc @tych0 @justincormack @riyazdf @ijc @deitch @arm64b

**Comment by tych0** [comment]
Works for me. I don't get the sense that #2445 was really something anyone was interested in :)

**Comment by rn** [comment]
I was interested in it because it's easier to just set some options for all kernels. but I don't quite like the downsides of it (harder to verify, harder to change in some cases) so it's kinda 50:50. The debian tooling is a little more interesting but requires some work and I'm not sure if it is worth it...

**Comment by riyazdf** [comment]
thanks @rn for the summary - I'm good with closing this issue

**Comment by tych0** [comment]
By harder to verify, do you mean that it's more complicated than a `git diff`?

The one thing that a "copy the whole file" approach makes difficult is merging kernel configs, so e.g. if I want a landlock + wireguard kernel, I have to do that by hand and can't do it automatically. But maybe that's okay :)

**Comment by tych0** [comment]
FWIW, I absolutely understand the desire to just check in the config and do stuff by hand. All the stuff I did was painful and complicated :)

**Comment by rn** [comment]
@tych0:
> By harder to verify, do you mean that it's more complicated than a git diff?
yes, specifically https://github.com/linuxkit/linuxkit/blob/master/kernel/Dockerfile#L89 is very easy :)

Combining new (under development) kernel features is indeed more painful with what we have now...

> All the stuff I did was painful and complicated :)

Indeed. I have done the same the past few days trying to align the kernel configs and also now trying to do 4.12 support...It's painful going through `make oldconfig` and then diff iterations.

In general, I think the debian tooling seems to hit a good middle ground. I like the prettifying of their split configs and also the fact that it groks the `Kconfig` files. Maybe I need to revisit my assessment of modifying the tools to our needs. We'd loose the ability to use `make menuconfig` but hey...

**Comment by rn** [comment]
Closing this for now. The current scheme kinda seems to work even if it is awkward for projects. We may have to revisit if we add more kernel configs, e.g. for LCOW or RT
